# Generated by Django 5.1.1 on 2024-09-10 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('types', models.CharField(choices=[('ML', 'MASALA'), ('GR', 'GINGER'), ('KT', 'KIWI'), ('PT', 'PLAIN'), ('ET', 'ELAICHI,')], max_length=2)),
            ],
        ),
    ]
