# Generated by Django 5.1.1 on 2024-09-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chai'),
    ]

    operations = [
        migrations.AddField(
            model_name='chai',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
